const products=[
{id:1,name:'Mango Paradise',cat:'smoothie',price:15000,desc:'Smoothie mangga creamy, segar, dan penuh rasa buah.',img:'https://images.unsplash.com/photo-1774428755046-f1a9b662ecb8?auto=format&fit=crop&fm=jpg&q=80&w=1000'},
{id:2,name:'Pineapple Splash',cat:'juice',price:15000,desc:'Jus nanas dingin dengan sensasi tropis yang menyegarkan.',img:'https://images.unsplash.com/photo-1523371054106-bbf80586c38c?auto=format&fit=crop&fm=jpg&q=80&w=1000'},
{id:3,name:'Coconut Island',cat:'coconut',price:17000,desc:'Air kelapa segar untuk menemani hari yang panas.',img:'https://images.unsplash.com/photo-1693665963913-10672e65d09b?auto=format&fit=crop&fm=jpg&q=80&w=1000'},
{id:4,name:'Strawberry Tropic',cat:'fresh',price:17000,desc:'Minuman strawberry creamy dengan topping buah segar.',img:'https://images.unsplash.com/photo-1648178628363-c8058d7d3423?auto=format&fit=crop&fm=jpg&q=80&w=1000'},
{id:5,name:'Tropical Citrus',cat:'juice',price:16000,desc:'Perpaduan jeruk segar dengan aroma herbal yang ringan.',img:'https://images.unsplash.com/photo-1523371054106-bbf80586c38c?auto=format&fit=crop&fm=jpg&q=80&w=1000'},
{id:6,name:'Mango Coconut',cat:'smoothie',price:18000,desc:'Mango creamy berpadu lembut dengan kesegaran kelapa.',img:'https://images.unsplash.com/photo-1774428755046-f1a9b662ecb8?auto=format&fit=crop&fm=jpg&q=80&w=1000'}
];
let cart=JSON.parse(localStorage.getItem('tropicalCart')||'[]');let activeProduct=null;let activeSize='Regular',activeSugar='50%';
const rupiah=n=>'Rp'+n.toLocaleString('id-ID');
const grid=document.getElementById('productGrid');
function renderProducts(){const cat=document.querySelector('.cat.active')?.dataset.cat||'all';const q=document.getElementById('search').value.toLowerCase();const list=products.filter(p=>(cat==='all'||p.cat===cat)&&p.name.toLowerCase().includes(q));grid.innerHTML=list.map(p=>`<article class="product"><img class="product-img" src="${p.img}" alt="${p.name}" loading="lazy"><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="price-row"><span class="price">${rupiah(p.price)}</span><button class="add-btn" onclick="openProduct(${p.id})" aria-label="Tambah ${p.name}">+</button></div></div></article>`).join('')||'<div class="empty">Minuman tidak ditemukan 🌴</div>'}
function save(){localStorage.setItem('tropicalCart',JSON.stringify(cart));renderCart();}
function openProduct(id){activeProduct=products.find(p=>p.id===id);activeSize='Regular';activeSugar='50%';document.getElementById('modalImg').src=activeProduct.img;document.getElementById('modalName').textContent=activeProduct.name;document.getElementById('modalDesc').textContent=activeProduct.desc;document.getElementById('modalPrice').textContent=rupiah(activeProduct.price);document.getElementById('modalCategory').textContent=activeProduct.cat.toUpperCase();document.querySelectorAll('.size,.sugar').forEach(x=>x.classList.remove('active'));document.querySelector('.size[data-size="Regular"]').classList.add('active');document.querySelector('.sugar[data-sugar="50%"]').classList.add('active');document.getElementById('topping').value='0';document.getElementById('productModal').classList.add('show')}
function renderCart(){const el=document.getElementById('cartItems');let count=cart.reduce((s,i)=>s+i.qty,0);document.getElementById('cartCount').textContent=count;let total=cart.reduce((s,i)=>s+i.price*i.qty,0);document.getElementById('cartTotal').textContent=rupiah(total);document.getElementById('checkoutTotal').textContent=rupiah(total);if(!cart.length){el.innerHTML='<div class="empty">Keranjang masih kosong 🥭<br>Yuk pilih minuman favoritmu!</div>';return}el.innerHTML=cart.map((i,idx)=>`<div class="cart-item"><img src="${i.img}" alt="${i.name}"><div><h4>${i.name}</h4><small>${i.size} • gula ${i.sugar}${i.topping?` • topping`:''}</small><div class="qty"><button onclick="changeQty(${idx},-1)">−</button><b>${i.qty}</b><button onclick="changeQty(${idx},1)">+</button></div></div><div><b>${rupiah(i.price*i.qty)}</b><button class="remove" onclick="removeItem(${idx})">Hapus</button></div></div>`).join('')}
function changeQty(idx,d){cart[idx].qty+=d;if(cart[idx].qty<=0)cart.splice(idx,1);save()};function removeItem(idx){cart.splice(idx,1);save()}
function showToast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function openDrawer(){document.getElementById('drawer').classList.add('open');document.getElementById('overlay').classList.add('show')};function closeDrawer(){document.getElementById('drawer').classList.remove('open');document.getElementById('overlay').classList.remove('show')}
document.querySelectorAll('.cat').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.cat').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts()}));document.getElementById('search').addEventListener('input',renderProducts);document.getElementById('cartBtn').onclick=openDrawer;document.getElementById('closeCart').onclick=closeDrawer;document.getElementById('overlay').onclick=closeDrawer;
document.querySelectorAll('.size').forEach(b=>b.onclick=()=>{document.querySelectorAll('.size').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeSize=b.dataset.size});document.querySelectorAll('.sugar').forEach(b=>b.onclick=()=>{document.querySelectorAll('.sugar').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeSugar=b.dataset.sugar});
document.getElementById('addToCart').onclick=()=>{const topping=Number(document.getElementById('topping').value);const price=activeProduct.price+(activeSize==='Large'?3000:0)+topping;const key=`${activeProduct.id}-${activeSize}-${activeSugar}-${topping}`;const found=cart.find(i=>i.key===key);if(found)found.qty++;else cart.push({key,name:activeProduct.name,img:activeProduct.img,size:activeSize,sugar:activeSugar,topping,price,qty:1});save();document.getElementById('productModal').classList.remove('show');showToast(`${activeProduct.name} masuk ke keranjang 🥭`)};
document.getElementById('modalClose').onclick=()=>document.getElementById('productModal').classList.remove('show');document.getElementById('checkoutClose').onclick=()=>document.getElementById('checkoutModal').classList.remove('show');
document.getElementById('checkoutBtn').onclick=()=>{if(!cart.length){showToast('Keranjang masih kosong 😊');return}document.getElementById('checkoutModal').classList.add('show');};
document.getElementById('placeOrder').onclick=()=>{const name=document.getElementById('customerName').value.trim();if(!name){showToast('Isi nama terlebih dahulu ya 😊');return}cart=[];save();document.getElementById('checkoutModal').classList.remove('show');closeDrawer();showToast(`Pesanan ${name} berhasil dibuat! 🎉`)};
document.getElementById('bestSellerBtn').onclick=()=>{document.getElementById('menu').scrollIntoView();setTimeout(()=>openProduct(1),400)};document.getElementById('promoBtn').onclick=()=>{document.getElementById('menu').scrollIntoView();showToast('Promo siap dipakai saat checkout 🎁')};
renderProducts();renderCart();
